# Site settings
title: Mukil Elango
email: mukilane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mukil's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mukilane.github.io" # the base hostname & protocol for your site
twitter_username: mukilane
github_username:  mukilane
greeting: "" # Display special messages
angular_version: "1.6.7" # Version of AngularJS used 
firebase_version: "4.8.1"
exclude: ["package.json",
          "node_modules",
          "gulpfile.js",
          "sw-precache-config.js",
          "vendor",
          "functions",
          "database.rules.json",
          "firebase.json",
          "Gemfile",
          "Gemfile.lock",
          "README.md"]
ampdir: amp # Amp files are stored here
# # Collections
# collections:
#   project:
#     output: true

# Data Page Generator
page_gen:
  - data: projects
    template: project
    dir: 'project'
    name: page_name

# Build settings
markdown: kramdown
